version: '3'

services:
  taskmanagerapp:
    depends_on:
      - db
    build: 
      context: .
      dockerfile: Dockerfile
    image: task-manager-docker
    container_name: taskmanagerapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/pokedex
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}
      DEFAULT_LIMIT: ${DEFAULT_LIMIT}
    # volumes:
    #   - ./:/var/www/pokedex

  db:
    image: mongo:5
    container_name: mongo-task-manager
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: task-manager
    volumes:
      - ./mongo:/data/db